name: ci

on:
  push:
    branches:
     - dev
  pull_request:
    branches:
     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5444:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build & Run Docker Images
      run: docker-compose up --build

    - name: Run ruff
      run: |
        ruff .

    - name: Run isort
      run: isort --check-only --diff .

    - name: Run pytest
      run: pytest

    - name: Stop Docker containers
      run: docker-compose down
